# Generated by Django 3.2.13 on 2023-06-11 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('due_data', models.DateField()),
                ('status', models.CharField(choices=[('APR', 'Pending'), ('APR', 'Approved'), ('APR', 'Rejected')], default='PND', max_length=3)),
                ('amount_paid', models.IntegerField()),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
