# Generated by Django 3.2.13 on 2023-06-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
