# Generated by Django 3.2.13 on 2023-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_due_data_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
