# Generated by Django 3.2.13 on 2023-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
